name: "Semver Compare"
author: "Graycore"
description: "A Github Action that compares two versions, semantically"

inputs:
  version:
    required: true
    description: "Original version"

  compare_against:
    required: true
    description: "The version to compare against"

outputs:
  result: # returns -1 if version is smaller than compare_against, 0 if they are equals and 1 if version is higher than compser_against
    description: 'The result of comparison'
    value: ${{ steps.semver-compare.outputs.result }}

runs:
  using: "composite"
  steps:
  - name: Semantically compare two versions 
    run: php -r "echo 'result=' . version_compare('${{ inputs.version }}', '${{ inputs.compare_against }}');" >> $GITHUB_OUTPUT
    shell: bash
    id: semver-compare

branding:
  icon: "code"
  color: "green"
